# Generated by Django 3.1.7 on 2021-03-14 17:12

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import project.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSObject',
            fields=[
                ('object_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.object')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='buckets.fsobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('project.object',),
            managers=[
                ('tagged', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('fsobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buckets.fsobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('buckets.fsobject',),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('fsobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buckets.fsobject')),
                ('_instance', models.FileField(null=True, storage=project.storage_backends.MediaStorage(), upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=('buckets.fsobject',),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('fsobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buckets.fsobject')),
            ],
            options={
                'abstract': False,
            },
            bases=('buckets.fsobject',),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='buckets.file')),
                ('_text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('buckets.file',),
        ),
    ]
